version: '3.7'

services:
  
  jenkins:
    image: jenkins/jenkins:latest
    user: root
    container_name: jenkins
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 5000:5000
      - 465:465
      - 587:587
    networks:
      - jenkins

networks:
  jenkins: