pipeline {
    agent none
    stages {
        stage ('Build') {
            agent {
                docker { image 'python:alpine3.19' }
            }
            steps {
                sh 'python -m py_compile App-Python/sources/add2vals.py App-Python/sources/calc.py'
            }
        }
        stage ('Teste') {
            agent {
                docker { image 'qnib/pytest' }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml App-Python/sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage ('Delivery') {
            agent {
                docker { 
                    image 'six8/pyinstaller-alpine'
                    args '--entrypoint='
                }
            }
            steps {
                sh 'pyinstaller --noconfirm --clean --onefile sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}